spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    view:
      prefix:
        /WEB-INF/jsp/
      suffix:
        .jsp
  datasource:
    url: ${SPRING_DATABASE_URL}
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
  profiles:
    activate: local
  application:
    name: Notifications-application
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USER}
    password: ${GMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
security:
  enable-csrf: false

server:
  port: 8080
bezkoder:
  app:
    jwtSecret:
      bezKoderSecretKey
    jwtExpirationMs:
      86400000

url:
  to:
    serverthc: ${URL_TO_CONSUMER}